// API actions
// Fetch all reminders
export const GET_REMINDERS = "GET_REMINDERS";
export const GET_REMINDERS_SUCCESS = "GET_REMINDERS_SUCCESS";
export const GET_REMINDERS_FAILURE = "GET_REMINDERS_FAILURE";

// Create a reminder
export const CREATE_REMINDER = "CREATE_REMINDER";
export const CREATE_REMINDER_SUCCESS = "CREATE_REMINDER_SUCCESS";
export const CREATE_REMINDER_FAILURE = "CREATE_REMINDER_FAILURE";

// Update a reminder
export const UPDATE_REMINDER = "UPDATE_REMINDER";
export const UPDATE_REMINDER_SUCCESS = "UPDATE_REMINDER_SUCCESS";
export const UPDATE_REMINDER_FAILURE = "UPDATE_REMINDER_FAILURE";

// Delete a reminder
export const DELETE_REMINDER = "DELETE_REMINDER";
export const DELETE_REMINDER_SUCCESS = "DELETE_REMINDER_SUCCESS";
export const DELETE_REMINDER_FAILURE = "DELETE_REMINDER_FAILURE";

// UI actions
export const FILTER_REMINDERS = "FILTER_REMINDERS";
export const UPDATE_FILTERED = "UPDATE_FILTERED";
export const UPDATE_FILTER = "UPDATE_FILTER";
