export const CREATE_REMINDER = 'CREATE_REMINDER';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';

export const FILTER_REMINDERS = 'FILTER_REMINDERS';
export const UPDATE_FILTER = 'UPDATE_FILTER';
